# HarvestBoost Configuration File
# ================================

# Detection radius for finding nearby farming players (in blocks)
detection:
  radius: 10
  # How often to check for nearby players (in ticks, 20 ticks = 1 second)
  check-interval: 100

# Growth multipliers based on number of nearby farming players
boosts:
  # Player count: multiplier (1.0 = normal speed, 2.0 = 2x speed)
  1: 1.0   # Solo farming - normal speed
  2: 1.25  # 2 players - 25% faster
  3: 1.5   # 3 players - 50% faster
  4: 1.75  # 4 players - 75% faster
  # Maximum boost level (caps at this many players)
  max-players: 4

# What should be boosted
enable:
  # Vanilla crops (wheat, carrots, potatoes, beetroot, melon, pumpkin, etc.)
  crops: true
  # Tree saplings and other plants
  saplings: true
  # Bamboo growth
  bamboo: true
  # Cactus and sugar cane
  tall-plants: true

# Visual and feedback settings
effects:
  # Show particle effects on boosted crops
  particles:
    enabled: true
    type: "HAPPY_VILLAGER"  # HAPPY_VILLAGER, COMPOSTER, or HEART
    amount: 3
    # How often particles appear (in ticks)
    interval: 60

  # Show actionbar messages to players
  actionbar:
    enabled: true
    # Update interval for actionbar (in ticks)
    update-interval: 40
    # Message format (%boost% = boost percentage, %players% = player count)
    format: "🌱 Growth boosted by %boost%% (%players% farmers nearby!)"

  # Play sound effects
  sounds:
    enabled: true
    # Sound when entering a boosted area
    enter-boost-area: "ENTITY_EXPERIENCE_ORB_PICKUP"
    # Sound when boost level changes
    boost-change: "BLOCK_NOTE_BLOCK_CHIME"
    volume: 0.5
    pitch: 1.2

# Advanced settings
advanced:
  # Minimum time a player must be in area to count (in ticks)
  minimum-presence-time: 100

  # Enable debug mode (shows extra info to ops)
  debug: false

  # World blacklist - worlds where the plugin won't work
  disabled-worlds:
    - "world_nether"
    - "world_the_end"

  # Maximum distance from crops to be considered "farming"
  farming-detection-radius: 3

  # Enable XP bonus for cooperative farming
  xp-bonus:
    enabled: true
    # Extra XP per boost level when harvesting
    per-level: 1

# Performance settings
performance:
  # Maximum number of crops to process per tick
  max-crops-per-tick: 50

  # Cache player locations for this many ticks
  location-cache-time: 20

# Messages
messages:
  prefix: "&a[HarvestBoost] "
  reload-success: "&aConfiguration reloaded successfully!"
  no-permission: "&cYou don't have permission to use this command."
  status-header: "&e--- Harvest Boost Status ---"
  status-players: "&7Players in area: &b%count%"
  status-boost: "&7Current boost: &a%boost%%"
  status-no-boost: "&7No boost active in this area."
  plugin-enabled: "&aHarvestBoost enabled! Farm together for faster growth!"
  plugin-disabled: "&cHarvestBoost has been disabled."